# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      # Install JAGS for Windows
      - name: Install JAGS for Windows
        if: runner.os == 'Windows'
        run: |
          curl.exe -L -o wjags.exe https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
          .\wjags.exe /S
          del wjags.exe
          echo "Checking JAGS installation..."
          jags --version || echo "JAGS installation failed!"
        shell: cmd

      # Install JAGS for macOS
      - name: Install JAGS for macOS
        if: matrix.config.os == 'macos-latest'
        run: |
          set -e
          if [[ "$(uname -m)" == "arm64" ]]; then
            echo "Building JAGS from source for macOS-arm64."
            brew install gcc
            curl -L -o jags-4.3.1.tar.gz https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/JAGS-4.3.1.tar.gz/download
            tar -xzf jags-4.3.1.tar.gz
            cd JAGS-4.3.1
            ./configure --build=aarch64-apple-darwin
            make
            sudo make install
            cd ..
          else
            brew update
            brew install jags
          fi
          echo "Checking JAGS installation..."
          jags --version || (echo "JAGS installation failed!" && exit 1)

      # Install JAGS for Ubuntu
      - name: Install JAGS for Ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y jags
          echo "Checking JAGS installation..."
          jags --version || echo "JAGS installation failed!"

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
